config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # getting all tasks
  # resources 'tasks'

  get 'tasks', to: 'tasks#index'
  # # getting one task
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  # # creating one task(2 requests)
  # # 1st request is to get form
  # # 2nd request is to post the params
  # get 'tasks/new', to: 'tasks#new'
  # post 'tasks', to: 'tasks#create'
  # # update a task
  # get 'tasks/:id/edit', to: 'tasks#edit'
  # patch 'tasks/:id', to: 'tasks#update'
  # # deleting a task
  # delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My tasks!</h1>
<form action="">
<% @tasks.each do |task| %>
  <% if task.completed %>
  <input type="checkbox" checked > <%= task.title %> <br>
  <% else %>
  <input type="checkbox" > <%= task.title %> <br>
  <% #We pass restaurant as an argument because we can extract its id. %>
  <% end %>
  <%= link_to "Details of task", task_path(task) %> <br>
<% end %>
</form>

app/views/tasks/show.html.erb
<h1> <%= @tasks.title %></h1>
<p><%= @tasks.details %></p>
<p><%= @tasks.completed %></p>

<%= link_to "Back to all Tasks", tasks_path %>